#---------------------------------------
StrChartSizeFactor = 'ChartSizeFactor'

strDate = 'timestamp'
strOpen = 'open'
strHigh = 'high'
strLow = 'low'
strClose = 'close'
strVolume = 'volume'

strAdjOpen = 'adjusted_open'
strAdjHigh = 'adjusted_high'
strAdjLow = 'adjusted_low'
strAdjClose = 'adjusted_close'

strNeighbor = 'neighbor'
#---------------------------------------

#---------------------------------------
strPredSoarCrashA = 'PredSoarCrashA'
strIsSoar = 'IsSoar'
strIsCrash = 'IsCrash'

strPredTrendA = 'PredTrendA'
strPredTrendB = 'PredTrendB'

strUpOrDown = 'UpOrDown'

strFuncName = 'FuncName'
strParam = 'Param'
#---------------------------------------

#---------------------------------------
# ML 
strData = 'Data'
strTarget = 'Target'
strPredictVal = 'PredictVal'
strPredictProbVal = 'PredictProbVal'
strScoreVal = 'ScoreVal'
strAnsVal = 'AnsVal'
#---------------------------------------

strCandle = 'Candle'
strBasic = 'Basic'

strColor = 'Color'
strWindow = 'Window'
strLineWidth = 'LineWidth'
strAlpha = 'Alpha'
strAreaColor = 'AreaColor'
strAreaAlpha = 'AreaAlpha'

strFuncName = 'FuncName'
strParam = 'Param'
strSMA = 'SMA'
strEMA = 'EMA'
strSMMA = 'SMMA' 
strDMA = 'DMA'
strMSTD = 'MSTD'
strMVAR = 'MVAR'
strRSV = 'RSV'
strRSI = 'RSI'
strMACD = 'MACD'
strMACD_DIF = 'MACD_DIF'
strMACD_DEM = 'MACD_DEM'
strMACD_OSC = 'MACD_OSC'
strWR = 'WR'
strCCI = 'CCI'
strTR = 'TR'
strATR = 'ATR'
strDMI = 'DMI'
strpDI = 'pDI'
strnDI = 'nDI'
strADX = 'ADX'
strADXR = 'ADXR'
strTEMA = 'TEMA'
strVR = 'VR'
strBollingerBands = 'BollingerBands'
strBollingerBand_upper = 'BollingerBandUpper'
strBollingerBand_lower = 'BollingerBandLower'
strKDJ = 'KDJ'
strKDJ_K = 'KDJ_K'
strKDJ_D = 'KDJ_D'
strKDJ_J = 'KDJ_J'
strChangeRate = 'ChangeRate'
strLogReturn = 'LogReturn'
strRollingMin = 'RollingMin'
strRollingMax = 'RollingMax'


strType = 'Type'
strValue = 'Value'

strComboBox = 'ComboBox'
strLineEdit = 'LineEdit'
strComboList = 'ComboList'
strButton = 'Button'
strAdd = 'Add'
strName = 'Name'

strPlotInAxPrice = 'PlotInAxPrice'
strYlabel = 'Ylabel'

strKColor = 'KColor'
strDColor = 'DColor'
strJColor = 'JColor'
strShortColor = 'ShortColor'
strLongColor = 'LongColor'
strShortWindow = 'ShortWindow'
strLongWindow = 'LongWindow'
strFastWindow = 'FastWindow'
strSlowWindow = 'SlowWindow'
strSignalWindow = 'SignalWindow'
strMACDColor = 'MACDColor'
strSignalColor = 'SignalColor'
strBarIncColor = 'BarIncColor'
strBarDecColor = 'BarDecColor'
strOverBColor = 'OverBColor'
strOverSColor = 'OverSColor'
strpDIColor = 'pDIColor'
strnDIColor = 'nDIColor'
strADXColor = 'ADXColor'
strADXRColor = 'ADXRColor'