# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'axistradecultform.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AxisTradeCultForm(object):
    def setupUi(self, AxisTradeCultForm):
        AxisTradeCultForm.setObjectName("AxisTradeCultForm")
        AxisTradeCultForm.resize(908, 533)
        self.centralWidget = QtWidgets.QWidget(AxisTradeCultForm)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 891, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.tabOverview = QtWidgets.QWidget()
        self.tabOverview.setObjectName("tabOverview")
        self.DisplayDate = QtWidgets.QDateEdit(self.tabOverview)
        self.DisplayDate.setGeometry(QtCore.QRect(10, 10, 110, 31))
        self.DisplayDate.setObjectName("DisplayDate")
        self.StockGroupsComboBox = QtWidgets.QComboBox(self.tabOverview)
        self.StockGroupsComboBox.setGeometry(QtCore.QRect(140, 10, 141, 31))
        self.StockGroupsComboBox.setObjectName("StockGroupsComboBox")
        self.UpdateButton = QtWidgets.QPushButton(self.tabOverview)
        self.UpdateButton.setGeometry(QtCore.QRect(490, 10, 101, 31))
        self.UpdateButton.setObjectName("UpdateButton")
        self.listView = QtWidgets.QListView(self.tabOverview)
        self.listView.setGeometry(QtCore.QRect(5, 50, 871, 381))
        self.listView.setObjectName("listView")
        self.UpdateProgressBar = QtWidgets.QProgressBar(self.tabOverview)
        self.UpdateProgressBar.setGeometry(QtCore.QRect(300, 10, 181, 31))
        self.UpdateProgressBar.setProperty("value", 0)
        self.UpdateProgressBar.setObjectName("UpdateProgressBar")
        self.SymbolLabel = QtWidgets.QLabel(self.tabOverview)
        self.SymbolLabel.setGeometry(QtCore.QRect(10, 50, 60, 31))
        self.SymbolLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SymbolLabel.setObjectName("SymbolLabel")
        self.OpenLabel = QtWidgets.QLabel(self.tabOverview)
        self.OpenLabel.setGeometry(QtCore.QRect(80, 50, 60, 31))
        self.OpenLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OpenLabel.setObjectName("OpenLabel")
        self.HightLabel = QtWidgets.QLabel(self.tabOverview)
        self.HightLabel.setGeometry(QtCore.QRect(150, 50, 60, 31))
        self.HightLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HightLabel.setObjectName("HightLabel")
        self.LowLabel = QtWidgets.QLabel(self.tabOverview)
        self.LowLabel.setGeometry(QtCore.QRect(220, 50, 60, 31))
        self.LowLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LowLabel.setObjectName("LowLabel")
        self.CloseLabel = QtWidgets.QLabel(self.tabOverview)
        self.CloseLabel.setGeometry(QtCore.QRect(290, 50, 60, 31))
        self.CloseLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CloseLabel.setObjectName("CloseLabel")
        self.VolumeLabel = QtWidgets.QLabel(self.tabOverview)
        self.VolumeLabel.setGeometry(QtCore.QRect(500, 50, 60, 31))
        self.VolumeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.VolumeLabel.setObjectName("VolumeLabel")
        self.ChangeCLabel = QtWidgets.QLabel(self.tabOverview)
        self.ChangeCLabel.setGeometry(QtCore.QRect(360, 50, 60, 31))
        self.ChangeCLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ChangeCLabel.setObjectName("ChangeCLabel")
        self.ChangeVLabel = QtWidgets.QLabel(self.tabOverview)
        self.ChangeVLabel.setGeometry(QtCore.QRect(570, 50, 60, 31))
        self.ChangeVLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ChangeVLabel.setObjectName("ChangeVLabel")
        self.AvgCLabel = QtWidgets.QLabel(self.tabOverview)
        self.AvgCLabel.setGeometry(QtCore.QRect(430, 50, 60, 31))
        self.AvgCLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AvgCLabel.setObjectName("AvgCLabel")
        self.AvgVLabel = QtWidgets.QLabel(self.tabOverview)
        self.AvgVLabel.setGeometry(QtCore.QRect(640, 50, 60, 31))
        self.AvgVLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AvgVLabel.setObjectName("AvgVLabel")
        self.StrikePrice1YLabel = QtWidgets.QLabel(self.tabOverview)
        self.StrikePrice1YLabel.setGeometry(QtCore.QRect(690, 50, 120, 31))
        self.StrikePrice1YLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.StrikePrice1YLabel.setObjectName("StrikePrice1YLabel")
        self.GraphSampleButton = QtWidgets.QPushButton(self.tabOverview)
        self.GraphSampleButton.setEnabled(True)
        self.GraphSampleButton.setGeometry(QtCore.QRect(820, 50, 51, 31))
        self.GraphSampleButton.setObjectName("GraphSampleButton")
        self.line = QtWidgets.QFrame(self.tabOverview)
        self.line.setGeometry(QtCore.QRect(20, 70, 791, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget.addTab(self.tabOverview, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        AxisTradeCultForm.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(AxisTradeCultForm)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 908, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuSetting = QtWidgets.QMenu(self.menuBar)
        self.menuSetting.setObjectName("menuSetting")
        AxisTradeCultForm.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(AxisTradeCultForm)
        self.statusBar.setObjectName("statusBar")
        AxisTradeCultForm.setStatusBar(self.statusBar)
        self.actionDataManager = QtWidgets.QAction(AxisTradeCultForm)
        self.actionDataManager.setObjectName("actionDataManager")
        self.menuSetting.addAction(self.actionDataManager)
        self.menuBar.addAction(self.menuSetting.menuAction())
        
        self.retranslateUi(AxisTradeCultForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AxisTradeCultForm)

    def retranslateUi(self, AxisTradeCultForm):
        _translate = QtCore.QCoreApplication.translate
        AxisTradeCultForm.setWindowTitle(_translate("AxisTradeCultForm", "AxisTradeCultForm"))
        self.UpdateButton.setText(_translate("AxisTradeCultForm", "Update"))
        self.SymbolLabel.setText(_translate("AxisTradeCultForm", "Symbol"))
        self.OpenLabel.setText(_translate("AxisTradeCultForm", "Open"))
        self.HightLabel.setText(_translate("AxisTradeCultForm", "High"))
        self.LowLabel.setText(_translate("AxisTradeCultForm", "Low"))
        self.CloseLabel.setText(_translate("AxisTradeCultForm", "Close"))
        self.VolumeLabel.setText(_translate("AxisTradeCultForm", "Volume"))
        self.ChangeCLabel.setText(_translate("AxisTradeCultForm", "Change"))
        self.ChangeVLabel.setText(_translate("AxisTradeCultForm", "Change"))
        self.AvgCLabel.setText(_translate("AxisTradeCultForm", "Avg(3M)"))
        self.AvgVLabel.setText(_translate("AxisTradeCultForm", "Avg(3M)"))
        self.StrikePrice1YLabel.setText(_translate("AxisTradeCultForm", "Strike Price(1Y)"))
        self.GraphSampleButton.setText(_translate("AxisTradeCultForm", "Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOverview), _translate("AxisTradeCultForm", "Overview"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("AxisTradeCultForm", "Tab 2"))
        self.menuSetting.setTitle(_translate("AxisTradeCultForm", "Setting"))
        self.actionDataManager.setText(_translate("AxisTradeCultForm", "DataManager"))

