strCandle = 'Candle'
strBasic = 'Basic'

strDate = 'Date'
strOpen = 'Open'
strHigh = 'High'
strLow = 'Low'
strClose = 'Close'
strVolume = 'Volume'

strColor = 'Color'
strWindow = 'Window'
strLineWidth = 'LineWidth'
strAlpha = 'Alpha'
strAreaColor = 'AreaColor'
strAreaAlpha = 'AreaAlpha'

strTechIndicatorKey = 'TechIndicatorKey'
strFuncName = 'FuncName'
strParam = 'Param'
strMA = 'MA'
strBollingerBands = 'BollingerBands'

strType = 'Type'
strValue = 'Value'

strComboBox = 'ComboBox'
strLineEdit = 'LineEdit'
strComboList = 'ComboList'
strButton = 'Button'
strAdd = 'Add'